version: '3.1'

services:
  jim:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=jim.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres
    depends_on:
      - jim-db
      
  jim-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=jim
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres