version: '3.6'

services:
  jim:
    container_name: jim-api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './:/usr/src/app'
    expose:
      - '5000'
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=supersecretkey
      - APP_SETTINGS=jim.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@jim-db:5432/jim_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@jim-db:5432/jim_test
    depends_on:
      - jim-db
      
  jim-db:
    container_name: jim-db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  nginx:
    container_name: jim-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - jim
